TEST_TAG = "TEST:"
SOLVE_TAG = "SOLVE:"
OUTPUT_TAG = "OUTPUT:"
NEXT_TAG = "NEXT:"

ACTIVE_IO_MODE = "query_mode"
PASSIVE_IO_MODE = "example_mode"
ACTIVE_MEMBERSHIP_MODE = "pair_in_set_mode"
PASSIVE_MEMBERSHIP_MODE = "labeled_pairs_mode"

PASSIVE_IO_ONESHOT_MODE = "example_mode_oneshot"
PASSIVE_MEMBERSHIP_ONESHOT_MODE = "labeled_pairs_mode_oneshot"

PASSIVE_MODES = {
    PASSIVE_IO_MODE,
    PASSIVE_MEMBERSHIP_MODE,
    PASSIVE_IO_ONESHOT_MODE,
    PASSIVE_MEMBERSHIP_ONESHOT_MODE,
}

MEMBERSHIP_MODES = {
    ACTIVE_MEMBERSHIP_MODE,
    PASSIVE_MEMBERSHIP_MODE,
    PASSIVE_MEMBERSHIP_ONESHOT_MODE,
}

ONESHOT_MODES = {
    PASSIVE_IO_ONESHOT_MODE,
    PASSIVE_MEMBERSHIP_ONESHOT_MODE,
}
