TEST_TAG = "TEST:"
SOLVE_TAG = "SOLVE:"
OUTPUT_TAG = "OUTPUT:"
NEXT_TAG = "NEXT:"

ACTIVE_IO_MODE = "active_inputs"
PASSIVE_IO_MODE = "passive_examples"
ACTIVE_MEMBERSHIP_MODE = "active_pair_checks"
PASSIVE_MEMBERSHIP_MODE = "passive_labeled_pairs"

PASSIVE_IO_ONESHOT_MODE = "passive_examples_oneshot"
PASSIVE_MEMBERSHIP_ONESHOT_MODE = "passive_labeled_pairs_oneshot"

PASSIVE_MODES = {
    PASSIVE_IO_MODE,
    PASSIVE_MEMBERSHIP_MODE,
    PASSIVE_IO_ONESHOT_MODE,
    PASSIVE_MEMBERSHIP_ONESHOT_MODE,
}

MEMBERSHIP_MODES = {
    ACTIVE_MEMBERSHIP_MODE,
    PASSIVE_MEMBERSHIP_MODE,
    PASSIVE_MEMBERSHIP_ONESHOT_MODE,
}

ONESHOT_MODES = {
    PASSIVE_IO_ONESHOT_MODE,
    PASSIVE_MEMBERSHIP_ONESHOT_MODE,
}
